# Generated by Django 5.0.4 on 2025-06-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='tournament',
        ),
        migrations.AlterUniqueTogether(
            name='participant',
            unique_together={('tournament', 'email')},
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='TournamentBracket',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
    ]
