# Generated by Django 5.0.4 on 2025-06-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_tournamentbracket_matches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='emergency_phone',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='team_name',
        ),
        migrations.AddField(
            model_name='participant',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('eliminated', 'Eliminated'), ('winner', 'Winner'), ('disqualified', 'Disqualified'), ('rejected', 'Rejected')], default='registered', max_length=20),
        ),
    ]
