# Generated by Django 5.0.4 on 2025-06-12 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_participant_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPlayer',
            fields=[
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chess_profile', serialize=False, to='app.participant')),
                ('fide_id', models.CharField(blank=True, max_length=20)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, choices=[('', 'No Title'), ('GM', 'Grandmaster (GM)'), ('IM', 'International Master (IM)'), ('FM', 'FIDE Master (FM)'), ('CM', 'Candidate Master (CM)'), ('WGM', 'Woman Grandmaster (WGM)'), ('WIM', 'Woman International Master (WIM)'), ('WFM', 'Woman FIDE Master (WFM)'), ('WCM', 'Woman Candidate Master (WCM)')], max_length=5)),
                ('fide_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('national_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('rapid_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('blitz_rating', models.PositiveIntegerField(blank=True, null=True)),
                ('section', models.CharField(choices=[('open', 'Open'), ('u1600', 'Under 1600'), ('u1400', 'Under 1400'), ('u1200', 'Under 1200'), ('u1000', 'Under 1000')], max_length=10)),
                ('federation', models.CharField(max_length=100)),
                ('club_academy', models.CharField(blank=True, max_length=200)),
                ('is_arbiter', models.BooleanField(default=False)),
                ('previous_tournaments', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Chess Player',
                'verbose_name_plural': 'Chess Players',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction ID or UPI reference number', max_length=100)),
                ('payment_screenshot', models.ImageField(blank=True, help_text='Screenshot of payment confirmation', upload_to='payment_proofs/')),
                ('ticket_count', models.PositiveIntegerField(default=1)),
                ('ticket_numbers', models.CharField(blank=True, help_text='Comma-separated ticket numbers', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.participant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.tournament')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_status'], name='app_transac_payment_acb0ad_idx'), models.Index(fields=['participant', 'tournament'], name='app_transac_partici_7dd4c6_idx')],
            },
        ),
    ]
