# Generated by Django 5.0.4 on 2025-06-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_chessplayer_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='payment_screenshot',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='payment_status',
        ),
    ]
