# Generated by Django 5.0.4 on 2025-06-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_participant_payment_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='app_transac_partici_7dd4c6_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='tournament',
        ),
        migrations.AddField(
            model_name='participant',
            name='transaction',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_record', to='app.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
