# Generated by Django 5.0.4 on 2025-06-14 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_transaction_app_transac_partici_7dd4c6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tournament_time',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
