# Generated by Django 5.0.4 on 2025-06-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_tournament_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
