# Generated by Django 5.0.4 on 2025-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_tournament_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
