# Generated by Django 5.0.4 on 2025-06-14 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_tournament_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('sports', 'Sports'), ('esports', 'Esports'), ('cultural', 'Cultural'), ('academic', 'Academic'), ('technology', 'Technology'), ('other', 'Other')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
