# Generated by Django 5.0.4 on 2025-06-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='wp',
            field=models.CharField(blank=True, help_text='WhatsApp number for updates', max_length=10),
        ),
    ]
