# Generated by Django 5.0.4 on 2025-06-15 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_participant_wp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(help_text='UPI ID for payment collection', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Name associated with the UPI ID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for updates and notifications', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='upi_id',
            field=models.ForeignKey(blank=True, help_text='UPI ID for payment collection', max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='app.upis'),
        ),
    ]
