# Generated by Django 5.0.4 on 2025-06-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_upis_alter_participant_email_tournament_upi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='upis',
            name='nickname',
            field=models.CharField(blank=True, help_text='Nickname for the UPI ID', max_length=100, null=True, unique=True),
        ),
    ]
