# Generated by Django 5.0.4 on 2025-06-23 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_upis_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament', to='app.tournament'),
        ),
    ]
