# Generated by Django 5.0.4 on 2025-06-23 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_participant_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='app.transaction'),
        ),
    ]
