# Generated by Django 5.0.4 on 2025-06-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_participant_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='logModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec', models.CharField(blank=True, max_length=100, null=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('sec_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
