# Generated by Django 5.0.4 on 2025-06-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_logmodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='optinWhatsapp',
            field=models.BooleanField(default=True),
        ),
    ]
